[CmdletBinding()]
param(
    [string]$Url,
    [string]$BatchFile,
    [string]$OutputDir = 'outputs/media',
    [string]$SubtitleLanguages = 'all,-live_chat',
    [switch]$IncludeAutoGenerated,
    [switch]$KeepVtt,
    [switch]$AllowPlaylist,
    [switch]$DryRun
)

. "$PSScriptRoot\MediaTools.ps1"

$subtitleDir = Ensure-Directory -Path (Join-Path $OutputDir 'subtitles')
$urls = Get-UrlList -Url $Url -BatchFile $BatchFile

foreach ($item in $urls) {
    $arguments = @(
        '--windows-filenames',
        '--no-overwrites',
        '--skip-download',
        '--write-subs',
        '--sub-langs', $SubtitleLanguages,
        '--sub-format', 'srt/vtt/best',
        '-o', (Join-Path $subtitleDir '%(upload_date>%Y-%m-%d)s_%(title).180B_[%(id)s].%(ext)s')
    )

    if ($IncludeAutoGenerated) {
        $arguments += '--write-auto-subs'
    }

    if (-not $KeepVtt) {
        $ffmpegPath = Get-FfmpegPath
        $arguments += @('--ffmpeg-location', $ffmpegPath, '--convert-subs', 'srt')
    }

    $arguments = Add-PlaylistPolicy -Arguments $arguments -AllowPlaylist:$AllowPlaylist
    $arguments += $item

    Invoke-YtDlp -Arguments $arguments -DryRun:$DryRun
}
