[CmdletBinding()]
param(
    [string]$ChannelUrl = 'https://www.youtube.com/@nicolasyounglive/videos',
    [string]$BatchFile = 'batch-list-nicolasyounglive.txt',
    [string]$OutputDir = 'outputs/media/nicolasyounglive',
    [string]$KnowledgeDir = 'knowledge/nicolasyounglive',
    [string]$KnowledgeTitle = 'Nicolas Young Live',
    [ValidateSet('mixed', 'education-tech')]
    [string]$ClassificationProfile = 'mixed',
    [string]$SubtitleLanguages = 'zh-TW,zh-Hant,zh-Hans,en,zh',
    [switch]$SkipSubtitles,
    [switch]$ContinueOnSubtitleError,
    [switch]$SkipSecondaryKnowledge
)

. "$PSScriptRoot\MediaTools.ps1"

$projectRoot = Get-ProjectRoot
$batchPath = Resolve-ProjectRelativePath -Path $BatchFile
$ytDlp = Get-YtDlpPath

Write-Host "Updating video list from $ChannelUrl"
$urls = & $ytDlp --flat-playlist --print 'https://www.youtube.com/watch?v=%(id)s' $ChannelUrl
if ($LASTEXITCODE -ne 0) {
    throw "yt-dlp failed while listing channel videos with exit code $LASTEXITCODE"
}

$urls = @($urls | Where-Object { $_ -match '^https://www\.youtube\.com/watch\?v=' } | Select-Object -Unique)
if ($urls.Count -eq 0) {
    throw "No video URLs found for $ChannelUrl"
}

$header = @(
    "# Source: $ChannelUrl"
    "# Updated: $((Get-Date).ToString('yyyy-MM-dd HH:mm:ss zzz'))"
    '# One public YouTube video URL per line.'
)
Set-Content -LiteralPath $batchPath -Value ($header + $urls) -Encoding UTF8
Write-Host "Wrote $($urls.Count) URLs to $batchPath"

$metadataScript = Join-Path $projectRoot 'scripts\metadata-only.ps1'
$subtitlesScript = Join-Path $projectRoot 'scripts\extract-subtitles.ps1'
$textSourcesScript = Join-Path $projectRoot 'scripts\build-text-sources.ps1'
$secondaryScript = Join-Path $projectRoot 'scripts\build-secondary-knowledge.ps1'

& $metadataScript -BatchFile $batchPath -OutputDir $OutputDir
if ($LASTEXITCODE -ne 0) {
    throw "metadata-only.ps1 failed with exit code $LASTEXITCODE"
}

if (-not $SkipSubtitles) {
    & $subtitlesScript -BatchFile $batchPath -OutputDir $OutputDir -SubtitleLanguages $SubtitleLanguages -IncludeAutoGenerated -ContinueOnError:$ContinueOnSubtitleError
    if ($LASTEXITCODE -ne 0) {
        throw "extract-subtitles.ps1 failed with exit code $LASTEXITCODE"
    }
}

& $textSourcesScript -MetadataDir (Join-Path $OutputDir 'metadata') -SubtitleDir (Join-Path $OutputDir 'subtitles') -OutputDir (Join-Path $OutputDir 'text-sources')
if ($LASTEXITCODE -ne 0) {
    throw "build-text-sources.ps1 failed with exit code $LASTEXITCODE"
}

if (-not $SkipSecondaryKnowledge) {
    & $secondaryScript -IndexPath (Join-Path $OutputDir 'text-sources\index.jsonl') -OutputDir $KnowledgeDir -CollectionTitle $KnowledgeTitle -ClassificationProfile $ClassificationProfile
    if ($LASTEXITCODE -ne 0) {
        throw "build-secondary-knowledge.ps1 failed with exit code $LASTEXITCODE"
    }
}

$metadataCount = (Get-ChildItem -LiteralPath (Resolve-ProjectRelativePath -Path (Join-Path $OutputDir 'metadata')) -File -Filter '*.info.json' | Measure-Object).Count
$subtitleCount = (Get-ChildItem -LiteralPath (Resolve-ProjectRelativePath -Path (Join-Path $OutputDir 'subtitles')) -File -Filter '*.srt' | Measure-Object).Count
$textSourceCount = (Get-ChildItem -LiteralPath (Resolve-ProjectRelativePath -Path (Join-Path $OutputDir 'text-sources')) -File -Filter '*.md' | Measure-Object).Count
$secondaryCount = if (-not $SkipSecondaryKnowledge) {
    $notesPath = Resolve-ProjectRelativePath -Path (Join-Path $KnowledgeDir 'notes')
    if (Test-Path -LiteralPath $notesPath -PathType Container) {
        (Get-ChildItem -LiteralPath $notesPath -File -Filter '*.md' | Measure-Object).Count
    } else {
        0
    }
} else {
    0
}

Write-Host "Channel videos: $($urls.Count)"
Write-Host "Metadata files: $metadataCount"
Write-Host "Subtitle files: $subtitleCount"
Write-Host "Text source files: $textSourceCount"
Write-Host "Secondary knowledge notes: $secondaryCount"
